#!/bin/bash
#
# Install recommendations and notes for Ubuntu 14.04
#

####################
### Repositories ###
####################

## Chrome
sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'

####################
###### Update ######
####################
sudo apt-get update

####################
### Remove bloat ###
####################
sudo apt-get remove --purge --ignore-missing gbrainy aisleriot gbrainy gnome-games-* gnome-sudoku gnomine libgme0 mahjongg bogofilter* empathy* thunderbird* remmina gwibber* tomboy avahi-daemon whoopsie samba* modemmanager rhythmbox* activity-log-manager-common python-zeitgeist zeitgeist-core deja-dup pidgin* apport*

####################
###### Install #####
####################
## GCC and G++
sudo apt-get install build-essential gfortran -y
sudo apt-get install gcc-4.6 gcc-4.7 gcc-4.8 g++-4.6 g++-4.7 g++-4.8 -y
# Tell update-alternatives about our compilers
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.6
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.7 70 --slave /usr/bin/g++ g++ /usr/bin/g++-4.7
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 80 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8
# Use this to switch compilers:
# sudo update-alternatives --config gcc
## Clang 3.5
sudo apt-get install clang-3.5

# MPI
sudo apt-get install autotools-dev openmpi-bin libopenmpi-dev -y
# C/C++ Libraries
sudo apt-get install cmake libboost-all-dev libfftw3-dev libsuitesparse-metis-dev -y
# Python
sudo apt-get install python-dev ipython python-setuptools python-pip python-scipy python-numpy python-matplotlib python-mrjob python-mpi4py python-cheetah python-opencv python-docutils -y
sudo easy_install StarCluster
# Java
sudo apt-get install openjdk-7-jdk -y
# Latex
sudo apt-get install texlive texlive-full texlive-latex-base texlive-latex-extra texstudio -y
# Chrome and Network
sudo apt-get install google-chrome-stable openssh-server sshfs autossh -y
# Git
sudo apt-get install git gitk colordiff -y
# Editors
sudo apt-get install emacs vim -y
# Visualization
sudo apt-get install libglew-dev freeglut3 freeglut3-dev libsdl1.2-dev -y
# Dropbox
sudo apt-get install nautilus-dropbox -y
# VLC
sudo apt-get install vlc -y
# Gimp
sudo apt-get install gimp gimp-plugin-registry -y
# Proprietary
sudo apt-get install ubuntu-restricted-extras -y

# TODO: CUDA?

####################
##### Upgrade ######
####################
sudo apt-get upgrade -y

####################
##### Configure ####
####################
# Git
git config --global user.name "Cris Cecka"
git config --global user.email "ccecka@seas.harvard.edu"
git config --global core.editor 'emacs -nw'
git config --global color.ui true

# Custom commands and improvements
echo "\n# Custom commands and aliases\n" >> ~/.bashrc
echo "# Colorize and include line number in grep" >> ~/.bashrc
echo "alias grep='grep -n --color=auto'" >> ~/.bashrc
echo "alias egrep='egrep -n --color=auto'" >> ~/.bashrc
echo "alias fgrep='fgrep -n --color=auto'" >> ~/.bashrc
echo "# Colorize diff" >> ~/.bashrc
echo "alias diff='colordiff'" >> ~/.bashrc

# Copy emacs configurations
cp .emacs ~/
cp -r .emacs.d ~/
